"""
This type stub file was generated by pyright.
"""

from _typeshed import SupportsRead
from collections.abc import Callable
from json.decoder import JSONDecodeError as JSONDecodeError, JSONDecoder as JSONDecoder
from json.encoder import JSONEncoder as JSONEncoder

__all__ = ["load", "JSONDecoder", "JSONDecodeError", "JSONEncoder"]

def load(
    fp: SupportsRead[str | bytes],
    *,
    cls: type[JSONDecoder] | None = ...,
    object_hook: Callable[[dict[str, str]], str] | None = ...,
    parse_float: Callable[[str], float] | None = ...,
    parse_int: Callable[[str], int] | None = ...,
    parse_constant: Callable[[str], str] | None = ...,
    object_pairs_hook: Callable[[list[tuple[str, str]]], str] | None = ...,
    **kwds: dict[str, str],
) -> dict[str, dict[str, dict[str, str]]]: ...
