"""
This type stub file was generated by pyright.
"""

from typing import Generic
from fastapi import FastAPI
from mcp.server.lowlevel.server import LifespanResultT
from fastmcp.server.openapi import ComponentFn as OpenAPIComponentFn, FastMCPOpenAPI, RouteMap, RouteMapFn as OpenAPIRouteMapFn

"""FastMCP - A more ergonomic interface for MCP servers."""

class FastMCP(Generic[LifespanResultT]):
    @classmethod
    def from_fastapi(cls, app: FastAPI, name: str | None = ..., route_maps: list[RouteMap] | None = ..., route_map_fn: OpenAPIRouteMapFn | None = ..., mcp_component_fn: OpenAPIComponentFn | None = ..., mcp_names: dict[str, str] | None = ..., httpx_client_kwargs: dict[str, str] | None = ..., tags: set[str] | None = ..., **settings: dict[str, str]) -> FastMCPOpenAPI:
        """
        Create a FastMCP server from a FastAPI application.
        """
        ...
