"""
This type stub file was generated by pyright.
"""

from ollama._client import AsyncClient, Client
from ollama._types import ChatResponse, EmbedResponse, EmbeddingsResponse, GenerateResponse, Image, ListResponse, Message, Options, ProcessResponse, ProgressResponse, RequestError, ResponseError, ShowResponse, StatusResponse, Tool, WebFetchResponse, WebSearchResponse
from typing import Callable, Literal, Mapping, Sequence
from pydantic.json_schema import JsonSchemaValue

__all__ = ['AsyncClient', 'ChatResponse', 'Client', 'EmbedResponse', 'EmbeddingsResponse', 'GenerateResponse', 'Image', 'ListResponse', 'Message', 'Options', 'ProcessResponse', 'ProgressResponse', 'RequestError', 'ResponseError', 'ShowResponse', 'StatusResponse', 'Tool', 'WebFetchResponse', 'WebSearchResponse']
def chat(
    model: str = '',
    messages: Sequence[Mapping[str, str] | Message] | None = None,
    *,
    tools: Sequence[Mapping[str, str] | Tool | Callable[..., str]] | None = None,
    stream: Literal[False] = False,
    think: bool | Literal['low', 'medium', 'high'] | None = None,
    format: Literal['', 'json'] | JsonSchemaValue | None = None,
    options: Mapping[str, str] | Options | None = None,
    keep_alive: float | str | None = None,
) -> ChatResponse: ...

