"""
This type stub file was generated by pyright.
"""

import sys
from pathlib import Path
from typing import Any, Callable, Dict, List, Literal, Mapping, Optional, Sequence, TypeVar, Union, overload
from pydantic.json_schema import JsonSchemaValue
from collections.abc import AsyncIterator, Iterator
from ollama._types import ChatResponse, EmbedResponse, EmbeddingsResponse, GenerateResponse, Image, ListResponse, Message, Options, ProcessResponse, ProgressResponse, ShowResponse, StatusResponse, Tool, WebFetchResponse, WebSearchResponse

if sys.version_info < (3, 9):
  ...
else:
  ...
__version__ = ...
T = TypeVar('T')
class BaseClient:
  def __init__(self, client, host: Optional[str] = ..., *, follow_redirects: bool = ..., timeout: Any = ..., headers: Optional[Mapping[str, str]] = ..., **kwargs) -> None:
    """
    Creates a httpx client. Default parameters are the same as those defined in httpx
    except for the following:
    - `follow_redirects`: True
    - `timeout`: None
    `kwargs` are passed to the httpx client.
    """
    ...
  


CONNECTION_ERROR_MESSAGE = ...
class Client(BaseClient):
  def __init__(self, host: Optional[str] = ..., **kwargs) -> None:
    ...
  
  @overload
  def generate(self, model: str = ..., prompt: str = ..., suffix: str = ..., *, system: str = ..., template: str = ..., context: Optional[Sequence[int]] = ..., stream: Literal[False] = ..., think: Optional[bool] = ..., raw: bool = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., images: Optional[Sequence[Union[str, bytes, Image]]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> GenerateResponse:
    ...
  
  @overload
  def generate(self, model: str = ..., prompt: str = ..., suffix: str = ..., *, system: str = ..., template: str = ..., context: Optional[Sequence[int]] = ..., stream: Literal[True] = ..., think: Optional[bool] = ..., raw: bool = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., images: Optional[Sequence[Union[str, bytes, Image]]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> Iterator[GenerateResponse]:
    ...
  
  def generate(self, model: str = ..., prompt: Optional[str] = ..., suffix: Optional[str] = ..., *, system: Optional[str] = ..., template: Optional[str] = ..., context: Optional[Sequence[int]] = ..., stream: bool = ..., think: Optional[bool] = ..., raw: Optional[bool] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., images: Optional[Sequence[Union[str, bytes, Image]]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> Union[GenerateResponse, Iterator[GenerateResponse]]:
    """
    Create a response using the requested model.

    Raises `RequestError` if a model is not provided.

    Raises `ResponseError` if the request could not be fulfilled.

    Returns `GenerateResponse` if `stream` is `False`, otherwise returns a `GenerateResponse` generator.
    """
    ...
  
  @overload
  def chat(self, model: str = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, tools: Optional[Sequence[Union[Mapping[str, Any], Tool, Callable]]] = ..., stream: Literal[False] = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> ChatResponse:
    ...
  
  @overload
  def chat(self, model: str = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, tools: Optional[Sequence[Union[Mapping[str, Any], Tool, Callable]]] = ..., stream: Literal[True] = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> Iterator[ChatResponse]:
    ...
  
  def chat(self, model: str = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, tools: Optional[Sequence[Union[Mapping[str, Any], Tool, Callable]]] = ..., stream: bool = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> Union[ChatResponse, Iterator[ChatResponse]]:
    """
    Create a chat response using the requested model.

    Args:
      tools:
        A JSON schema as a dict, an Ollama Tool or a Python Function.
        Python functions need to follow Google style docstrings to be converted to an Ollama Tool.
        For more information, see: https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings
      stream: Whether to stream the response.
      format: The format of the response.

    Example:
      def add_two_numbers(a: int, b: int) -> int:
        '''
        Add two numbers together.

        Args:
          a: First number to add
          b: Second number to add

        Returns:
          int: The sum of a and b
        '''
        return a + b

      client.chat(model='llama3.2', tools=[add_two_numbers], messages=[...])

    Raises `RequestError` if a model is not provided.

    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ChatResponse` if `stream` is `False`, otherwise returns a `ChatResponse` generator.
    """
    ...
  
  def embed(self, model: str = ..., input: Union[str, Sequence[str]] = ..., truncate: Optional[bool] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ..., dimensions: Optional[int] = ...) -> EmbedResponse:
    ...
  
  def embeddings(self, model: str = ..., prompt: Optional[str] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> EmbeddingsResponse:
    """
    Deprecated in favor of `embed`.
    """
    ...
  
  @overload
  def pull(self, model: str, *, insecure: bool = ..., stream: Literal[False] = ...) -> ProgressResponse:
    ...
  
  @overload
  def pull(self, model: str, *, insecure: bool = ..., stream: Literal[True] = ...) -> Iterator[ProgressResponse]:
    ...
  
  def pull(self, model: str, *, insecure: bool = ..., stream: bool = ...) -> Union[ProgressResponse, Iterator[ProgressResponse]]:
    """
    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ProgressResponse` if `stream` is `False`, otherwise returns a `ProgressResponse` generator.
    """
    ...
  
  @overload
  def push(self, model: str, *, insecure: bool = ..., stream: Literal[False] = ...) -> ProgressResponse:
    ...
  
  @overload
  def push(self, model: str, *, insecure: bool = ..., stream: Literal[True] = ...) -> Iterator[ProgressResponse]:
    ...
  
  def push(self, model: str, *, insecure: bool = ..., stream: bool = ...) -> Union[ProgressResponse, Iterator[ProgressResponse]]:
    """
    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ProgressResponse` if `stream` is `False`, otherwise returns a `ProgressResponse` generator.
    """
    ...
  
  @overload
  def create(self, model: str, quantize: Optional[str] = ..., from_: Optional[str] = ..., files: Optional[Dict[str, str]] = ..., adapters: Optional[Dict[str, str]] = ..., template: Optional[str] = ..., license: Optional[Union[str, List[str]]] = ..., system: Optional[str] = ..., parameters: Optional[Union[Mapping[str, Any], Options]] = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, stream: Literal[False] = ...) -> ProgressResponse:
    ...
  
  @overload
  def create(self, model: str, quantize: Optional[str] = ..., from_: Optional[str] = ..., files: Optional[Dict[str, str]] = ..., adapters: Optional[Dict[str, str]] = ..., template: Optional[str] = ..., license: Optional[Union[str, List[str]]] = ..., system: Optional[str] = ..., parameters: Optional[Union[Mapping[str, Any], Options]] = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, stream: Literal[True] = ...) -> Iterator[ProgressResponse]:
    ...
  
  def create(self, model: str, quantize: Optional[str] = ..., from_: Optional[str] = ..., files: Optional[Dict[str, str]] = ..., adapters: Optional[Dict[str, str]] = ..., template: Optional[str] = ..., license: Optional[Union[str, List[str]]] = ..., system: Optional[str] = ..., parameters: Optional[Union[Mapping[str, Any], Options]] = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, stream: bool = ...) -> Union[ProgressResponse, Iterator[ProgressResponse]]:
    """
    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ProgressResponse` if `stream` is `False`, otherwise returns a `ProgressResponse` generator.
    """
    ...
  
  def create_blob(self, path: Union[str, Path]) -> str:
    ...
  
  def list(self) -> ListResponse:
    ...
  
  def delete(self, model: str) -> StatusResponse:
    ...
  
  def copy(self, source: str, destination: str) -> StatusResponse:
    ...
  
  def show(self, model: str) -> ShowResponse:
    ...
  
  def ps(self) -> ProcessResponse:
    ...
  
  def web_search(self, query: str, max_results: int = ...) -> WebSearchResponse:
    """
    Performs a web search

    Args:
      query: The query to search for
      max_results: The maximum number of results to return (default: 3)

    Returns:
      WebSearchResponse with the search results
    Raises:
      ValueError: If OLLAMA_API_KEY environment variable is not set
    """
    ...
  
  def web_fetch(self, url: str) -> WebFetchResponse:
    """
    Fetches the content of a web page for the provided URL.

    Args:
      url: The URL to fetch

    Returns:
      WebFetchResponse with the fetched result
    """
    ...
  


class AsyncClient(BaseClient):
  def __init__(self, host: Optional[str] = ..., **kwargs) -> None:
    ...
  
  async def web_search(self, query: str, max_results: int = ...) -> WebSearchResponse:
    """
    Performs a web search

    Args:
      query: The query to search for
      max_results: The maximum number of results to return (default: 3)

    Returns:
      WebSearchResponse with the search results
    """
    ...
  
  async def web_fetch(self, url: str) -> WebFetchResponse:
    """
    Fetches the content of a web page for the provided URL.

    Args:
      url: The URL to fetch

    Returns:
      WebFetchResponse with the fetched result
    """
    ...
  
  @overload
  async def generate(self, model: str = ..., prompt: str = ..., suffix: str = ..., *, system: str = ..., template: str = ..., context: Optional[Sequence[int]] = ..., stream: Literal[False] = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., raw: bool = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., images: Optional[Sequence[Union[str, bytes, Image]]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> GenerateResponse:
    ...
  
  @overload
  async def generate(self, model: str = ..., prompt: str = ..., suffix: str = ..., *, system: str = ..., template: str = ..., context: Optional[Sequence[int]] = ..., stream: Literal[True] = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., raw: bool = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., images: Optional[Sequence[Union[str, bytes, Image]]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> AsyncIterator[GenerateResponse]:
    ...
  
  async def generate(self, model: str = ..., prompt: Optional[str] = ..., suffix: Optional[str] = ..., *, system: Optional[str] = ..., template: Optional[str] = ..., context: Optional[Sequence[int]] = ..., stream: bool = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., raw: Optional[bool] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., images: Optional[Sequence[Union[str, bytes, Image]]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> Union[GenerateResponse, AsyncIterator[GenerateResponse]]:
    """
    Create a response using the requested model.

    Raises `RequestError` if a model is not provided.

    Raises `ResponseError` if the request could not be fulfilled.

    Returns `GenerateResponse` if `stream` is `False`, otherwise returns an asynchronous `GenerateResponse` generator.
    """
    ...
  
  @overload
  async def chat(self, model: str = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, tools: Optional[Sequence[Union[Mapping[str, Any], Tool, Callable]]] = ..., stream: Literal[False] = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> ChatResponse:
    ...
  
  @overload
  async def chat(self, model: str = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, tools: Optional[Sequence[Union[Mapping[str, Any], Tool, Callable]]] = ..., stream: Literal[True] = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> AsyncIterator[ChatResponse]:
    ...
  
  async def chat(self, model: str = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, tools: Optional[Sequence[Union[Mapping[str, Any], Tool, Callable]]] = ..., stream: bool = ..., think: Optional[Union[bool, Literal['low', 'medium', 'high']]] = ..., format: Optional[Union[Literal['', 'json'], JsonSchemaValue]] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> Union[ChatResponse, AsyncIterator[ChatResponse]]:
    """
    Create a chat response using the requested model.

    Args:
      tools:
        A JSON schema as a dict, an Ollama Tool or a Python Function.
        Python functions need to follow Google style docstrings to be converted to an Ollama Tool.
        For more information, see: https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings
      stream: Whether to stream the response.
      format: The format of the response.

    Example:
      def add_two_numbers(a: int, b: int) -> int:
        '''
        Add two numbers together.

        Args:
          a: First number to add
          b: Second number to add

        Returns:
          int: The sum of a and b
        '''
        return a + b

      await client.chat(model='llama3.2', tools=[add_two_numbers], messages=[...])

    Raises `RequestError` if a model is not provided.

    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ChatResponse` if `stream` is `False`, otherwise returns an asynchronous `ChatResponse` generator.
    """
    ...
  
  async def embed(self, model: str = ..., input: Union[str, Sequence[str]] = ..., truncate: Optional[bool] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ..., dimensions: Optional[int] = ...) -> EmbedResponse:
    ...
  
  async def embeddings(self, model: str = ..., prompt: Optional[str] = ..., options: Optional[Union[Mapping[str, Any], Options]] = ..., keep_alive: Optional[Union[float, str]] = ...) -> EmbeddingsResponse:
    """
    Deprecated in favor of `embed`.
    """
    ...
  
  @overload
  async def pull(self, model: str, *, insecure: bool = ..., stream: Literal[False] = ...) -> ProgressResponse:
    ...
  
  @overload
  async def pull(self, model: str, *, insecure: bool = ..., stream: Literal[True] = ...) -> AsyncIterator[ProgressResponse]:
    ...
  
  async def pull(self, model: str, *, insecure: bool = ..., stream: bool = ...) -> Union[ProgressResponse, AsyncIterator[ProgressResponse]]:
    """
    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ProgressResponse` if `stream` is `False`, otherwise returns a `ProgressResponse` generator.
    """
    ...
  
  @overload
  async def push(self, model: str, *, insecure: bool = ..., stream: Literal[False] = ...) -> ProgressResponse:
    ...
  
  @overload
  async def push(self, model: str, *, insecure: bool = ..., stream: Literal[True] = ...) -> AsyncIterator[ProgressResponse]:
    ...
  
  async def push(self, model: str, *, insecure: bool = ..., stream: bool = ...) -> Union[ProgressResponse, AsyncIterator[ProgressResponse]]:
    """
    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ProgressResponse` if `stream` is `False`, otherwise returns a `ProgressResponse` generator.
    """
    ...
  
  @overload
  async def create(self, model: str, quantize: Optional[str] = ..., from_: Optional[str] = ..., files: Optional[Dict[str, str]] = ..., adapters: Optional[Dict[str, str]] = ..., template: Optional[str] = ..., license: Optional[Union[str, List[str]]] = ..., system: Optional[str] = ..., parameters: Optional[Union[Mapping[str, Any], Options]] = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, stream: Literal[False] = ...) -> ProgressResponse:
    ...
  
  @overload
  async def create(self, model: str, quantize: Optional[str] = ..., from_: Optional[str] = ..., files: Optional[Dict[str, str]] = ..., adapters: Optional[Dict[str, str]] = ..., template: Optional[str] = ..., license: Optional[Union[str, List[str]]] = ..., system: Optional[str] = ..., parameters: Optional[Union[Mapping[str, Any], Options]] = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, stream: Literal[True] = ...) -> AsyncIterator[ProgressResponse]:
    ...
  
  async def create(self, model: str, quantize: Optional[str] = ..., from_: Optional[str] = ..., files: Optional[Dict[str, str]] = ..., adapters: Optional[Dict[str, str]] = ..., template: Optional[str] = ..., license: Optional[Union[str, List[str]]] = ..., system: Optional[str] = ..., parameters: Optional[Union[Mapping[str, Any], Options]] = ..., messages: Optional[Sequence[Union[Mapping[str, Any], Message]]] = ..., *, stream: bool = ...) -> Union[ProgressResponse, AsyncIterator[ProgressResponse]]:
    """
    Raises `ResponseError` if the request could not be fulfilled.

    Returns `ProgressResponse` if `stream` is `False`, otherwise returns a `ProgressResponse` generator.
    """
    ...
  
  async def create_blob(self, path: Union[str, Path]) -> str:
    ...
  
  async def list(self) -> ListResponse:
    ...
  
  async def delete(self, model: str) -> StatusResponse:
    ...
  
  async def copy(self, source: str, destination: str) -> StatusResponse:
    ...
  
  async def show(self, model: str) -> ShowResponse:
    ...
  
  async def ps(self) -> ProcessResponse:
    ...
  


